server:
  port: 8888

spring:
  application:
    name: config
  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ambitionman868/cloud.git #配置git仓库地址
          searchPaths: /config #配置仓库路径
          username: ambitionman868 #访问git仓库的用户名
          password:  #访问git仓库的用户密码
      label: master #配置仓库的分支

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false